various fixes and features: synchronize rules from local dir, check service status after restart, rename port ansible var, add become where needed allow use of SSL elasticsearch cluster connection
OT-OSM/elastalert pull request #3
Opened 2020-12-28 14:32 UTC by NanoPish

* automatic rules upload -> local dir {{ elastalert_local_rules_dir }}
* automatic rules upload: delete rules on server that are not in the {{ elastalert_local_rules_dir }} ansible machine directory (=> synchronize ~= rsync)
* automatic service status check after restart -> see handlers
* add become: yes everywhere it is needed to avoid unecessary become
* rename {{ port }} to {{ es_port }} to make it clearer
* SSL elasticsearch connection

2021-01-06 14:44 UTC, NanoPish commented
Hey, are you interested in those features?

2021-01-07 06:27 UTC, iamabhishek-dubey requested changes
Just one change

2021-01-07 06:27 UTC, iamabhishek-dubey commented on vars/main.yml
> +es_port: 9300
Let's keep it 9200 because 9300 generally is for TCP connections

2021-01-11 11:34 UTC, NanoPish commented
Hey! I updated the documentation with all the variables related to automatically uploading and deleting rules, using SSL...
I also added examples and version change in the README.md.
I let you tag the release

2021-01-11 11:35 UTC, NanoPish commented
I also tested the playbook with and without rule upload to check everything is okay
tell me if its all good

2021-01-11 11:51 UTC, iamabhishek-dubey commented
All things look good, can you resolve merge conflicts?

2021-01-11 11:55 UTC, NanoPish commented
done

2021-02-05 13:11 UTC, NanoPish commented
good?

2021-02-05 13:13 UTC, iamabhishek-dubey approved these changes

2021-02-05 13:13 UTC, merged

2021-02-05 13:13 UTC, iamabhishek-dubey commented
Thanks for your contribution!!